name: HTML Tidy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  prettier:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{html,js,md}
  tidy:
    if: always()
    needs: prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Cache packages
        uses: actions/cache@v3
        id: cache-packages
      - name: Tidy code
        run: |
          sudo apt install tidy
          tidy --indent auto --indent-spaces 2 --wrap 0 -o index.html index.html
      - name: Commit files and push changes
        continue-on-error: true
        run: |
          git config --local user.email "tgrothe[bot]@users.noreply.github.com"
          git config --local user.name "tgrothe[bot]"
          git commit -a -m "Add changes from html tidy" && git push
