name: Auto Create PR
on:
  push:
    branches:
      - main
jobs:
  createPr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Make changes to pull request here
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
